language: python3

# you can use a different version of Python
python: "3.9"

# don't clone more than necessary
git:
  depth: 1

# Install dependencies
install:
  - pip3 install -r requirements.txt

# script to run tests. Script can have many commands, one per line.
script:
  - coverage run -m unittest discover -p "*_tests.py"

after_script:
  - bash <(curl -s https://codecov.io/bash)
